[general]
host = "0.0.0.0"
port = 6432
autoreload = 15000
worker_threads = 8
admin_username = "pgcat"
admin_password = "pgcat"

[pools.pgbench]
pool_mode = "transaction"
connect_timeout = 3000

[pools.pgbench.users.0]
username = "pgbench"
password = "pgbench"
pool_size = 24
min_pool_size = 24
statement_timeout = 0

[pools.pgbench.shards.0]
database = "pgbench"
servers = [
    [ "127.0.0.1", 5432, "replica" ]
]